### ISSUE TITLE
Add carrier Be-10/Be-9 ratio and uncertainty to the be_carrier table

### ISSUE THREAD

**Issue by beryllium10** [cosmolab/chemdb#1]
It would be good to add two new columns to the be_carrier table, one for the carrier isotope ratio and another for uncertainty in the isotope ratio.  This information is needed for properly calculating sample Be-10 concentrations when measured sample ratios are low, and the carrier Be-10 contribution to the total Be-10 becomes significant.

**Comment by zploskey** [comment]
This is simple enough to add. We can add two columns to the BeCarrier
table. Perhaps we should display the 10/9 ratio on the page where we do
carrier addition and on batch reports.

I am proposing adding "r10to9" and "r10to9_error", which matches how this
was handled for AMS measurements. Should we go ahead and add corresponding
entries to AlCarrier?

**Comment by beryllium10** [comment]
Hi again Zach,

> This is simple enough to add. We can add two columns to the BeCarrier
> table. Perhaps we should display the 10/9 ratio on the page where we do
> carrier addition and on batch reports.

If it's easy to modify those pages.  No reason not to, but less 
important than getting the information into the DB.

> I am proposing adding "r10to9" and "r10to9_error", which matches how this
> was handled for AMS measurements. Should we go ahead and add corresponding
> entries to AlCarrier?

Those names make good sense, and match the AMS table equivalents.  I'd 
say let's add equivalents to the al_carrier table, for consistency.  Up 
to now there's never been any hope of measuring carrier-level 
Al-26/Al-27 ratios, but it now looks possible with PRIME and ANU 
running AlO- beams.  I've always assumed that Al carriers have ratios 
below E-15, because we don't expect there to be any 'environmental' 
Al-26 around (either meteoric or nucleogenic), especially where 
industrial Al is mined.  But it will be interesting to see if anything 
turns up once it starts getting measured.

Cheers,  John

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cosmolab/chemdb/issues/1#issuecomment-174085922

---

When your only tool is a hammer, everything looks like a rock

John Stone
Department of Earth and Space Sciences
University of Washington                     Phone + 1 206 221-6332
Box 351310, 70 Johnson Hall                  Lab   + 1 206 221-6383
Seattle, WA 98195-1310, USA                  Fax   + 1 206 543-0489
